//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArrearsManagementSystemApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arrear
    {
        public int ArrearId { get; set; }
        public int UserId { get; set; }
        public int StoreId { get; set; }
        public System.DateTime Dates { get; set; }
        public System.TimeSpan Times { get; set; }
        public double Amount { get; set; }
    
        public virtual Store Store { get; set; }
        public virtual User User { get; set; }
    }
}
